set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_DOCUMENTATION OFF CACHE BOOL "" FORCE)
set(BUILD_DISCRETEREMESHING ON CACHE BOOL "" FORCE)
set(BUILD_VOLUMEPROCESSING OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES ON CACHE BOOL "" FORCE)
set(BUILD_COMMON_EXAMPLES OFF CACHE BOOL "" FORCE)

add_subdirectory(
  "${CMAKE_CURRENT_LIST_DIR}/../vendor/ACVD"
  "${CMAKE_CURRENT_BINARY_DIR}/vendor/ACVD"
)
